stages: [mirror]

variables:
  GIT_DEPTH: "0"

mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.email "mirror@linuxguy.de"
    - git config --global user.name "GitLab Mirror"
  script:
    - git clone --mirror . repo.git
    - cd repo.git
    - >
      git push --force --prune
      "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${CI_PROJECT_NAME}.git"
      "+refs/heads/*:refs/heads/*"
      "+refs/tags/*:refs/tags/*"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'