name: Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: docker
    container:
      image: docker:cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show Docker version
        run: docker version

      - name: Build Docker image
        run: |
          docker build -t zyxel-5g-exporter:test .
